#
# https://code.chs.usgs.gov/coupled/wphast
# SRC 2020-12-02T18:39:55-07:00
# XXXSRC 2021-10-30T14:30:15-06:00 -- changed pull to squash -- HEAD:5148078b4c1ceba454932038c8b6c3228f916564
#
image: ${CI_REGISTRY}/coupled/containers/buildpack-deps:bionic-scm

stages:
  - sync

before_script:
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY_ENC}" | base64 --decode | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan ${CI_SERVER_HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "darth@empire.com"
  - git config --global user.name "Darth Vader"
 
subtree-sync:
  stage: sync

  ##
  ## Only run if on the master branch and the variable GROUP is set
  ##
  ## change this to
  ## only:
  ##  - master@$GROUP/wphast
  ## and set GROUP to coupled before merge
  only:
    refs:
      - master
    variables:
      - $GROUP
  
  script:
    ##
    ## Must re-clone in order for the subtree merge to work
    ## tried re-setting the url for the origin but didn't work
    ##
    - cd ..
    - rm -rf ${CI_PROJECT_NAME}
    - git clone git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
    - cd ${CI_PROJECT_NAME}
    
    ##
    ## Sync subtrees
    ##  
    - |
      #!/bin/bash -ex
      #
      # WPhast\                    git@${CI_SERVER_HOST}:${GROUP}/wphast.git
      # ├─msi\                     ├─msi
      # │ └─phast                  │ └─phast
      # │   ├─database             │   ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-database.git               msi/phast/database
      # │   ├─doc\                 │   ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-doc.git                      msi/phast/doc
      # │   │ └─phreeqc3-doc\      │   │ └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-doc.git                  msi/phast/doc/phreeqc3-doc
      # │   └─examples             │   └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-examples.git                 msi/phast/examples
      # └─src\                     └─src
      #   ├─gridctrl\                ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/wphast-src-gridctrl.git               src/gridctrl
      #   ├─phast                    ├─phast
      #   │ └─PhreeqcRM              │ └─PhreeqcRM
      #   │   └─src                  │   └─src
      #   │     └─IPhreeqcPhast      │     └─IPhreeqcPhast
      #   │       └─IPhreeqc         │       └─IPhreeqc
      #   │         └─phreeqcpp      │         └─phreeqcpp
      #   │           └─common       │           └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-src-common.git   src/phast/PhreeqcRM/src/IPhreeqcPhast/IPhreeqc/phreeqcpp/common
      #   └─srcinput\                └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-src-phastinput.git             src/srcinput
      #     └─common<SYMLINKD>         └─common<SYMLINKD>\                                                           [..\phast\PhreeqcRM\src\IPhreeqcPhast\IPhreeqc\phreeqcpp\common]

      git_subtree() {
        git subtree "${1}" --prefix="${2}" "${4}" master 2>&1 | grep -v "^[[:digit:]].*/[[:digit:]].*"
      }

      declare -A urls=( \
        ["phreeqc3-database"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-database.git" \
        ["phast3-doc"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-doc.git" \
        ["phast3-examples"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-examples.git" \
        ["wphast-src-gridctrl"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/wphast-src-gridctrl.git" \
        ["phreeqc3-src-common"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-src-common.git" \
        ["phast3-src-phastinput"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/phast3-src-phastinput.git" \
      )

      declare -A prefixes=( \
        ["phreeqc3-database"]="msi/phast/database" \
        ["phast3-doc"]="msi/phast/doc" \
        ["phast3-examples"]="msi/phast/examples" \
        ["wphast-src-gridctrl"]="src/gridctrl" \
        ["phreeqc3-src-common"]="src/phast/PhreeqcRM/src/IPhreeqcPhast/IPhreeqc/phreeqcpp/common" \
        ["phast3-src-phastinput"]="src/srcinput" \
      )

      export GIT_EDITOR=true

      for remote in "${!urls[@]}"; do
        git_subtree "pull" "${prefixes[$remote]}" "$remote" "${urls[$remote]}"
      done

      for remote in "${!urls[@]}"; do
        git_subtree "push" "${prefixes[$remote]}" "$remote" "${urls[$remote]}"
      done

      git status
      git push origin master

## Downstream Projects
## none

## Upstream Projects
## phast3-doc            https://code.chs.usgs.gov/coupled/subtrees/phast3-doc
## phast3-examples       https://code.chs.usgs.gov/coupled/subtrees/phast3-examples
## phast3-src-phastinput https://code.chs.usgs.gov/coupled/subtrees/phast3-src-phastinput
## phreeqc3-database     https://code.chs.usgs.gov/coupled/subtrees/phreeqc3-database
## phreeqc3-src-common   https://code.chs.usgs.gov/coupled/subtrees/phreeqc3-src-common
## wphast-src-gridctrl   https://code.chs.usgs.gov/coupled/subtrees/wphast-src-gridctrl
